version: '3'


services:
    mongo-db-container:
        image: mongo
        restart: always
        ports:
            - "27017:27017"
    my-application-container:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on: 
            mongo-db-container
        ports: 
            - "8080:3000"
        restart: always